version: '2'
services:
  sequelize-pagination-datastore:
    image: busybox
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:rw
    container_name: sequelize-pagination-datastore
  sequelize-pagination-pg:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    ports:
      - "127.0.0.1:5432:5432"
    container_name: sequelize-pagination-pg
    volumes_from:
      - sequelize-pagination-datastore
