version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:4.8.7
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: testdb
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --prefer-offline
      - run:
          name: Install codeclimate reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./cc-test-reporter
      - run:
          name: Wait for postgres
          command: |
            sleep 5
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: lint and test
          command: |
            yarn run lint
            ./cc-test-reporter before-build
            yarn run test
            ./cc-test-reporter after-build --exit-code $?
          environment:
            TEST_DB: postgres://root:@127.0.0.1:5432/testdb
            CC_TEST_REPORTER_ID: 338bacf1f7de2c7c1973b2641bd717559655b0c892503773457b9271036171f5

workflows:
  version: 2
  build:
    jobs:
      - build
