version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:4.8.7
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: testdb
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --prefer-offline
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Install psql
          command: sudo apt-get install postgresql-client
      - run:
          name: Wait for postgres
          command: |
            sleep 5
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: lint and test
          command: yarn run ci
          environment:
            TEST_DB: postgres://root:@127.0.0.1:5432/testdb

workflows:
  version: 2
  build:
    jobs:
      - build
